//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToutorialBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistory
    {
        public int HistoryId { get; set; }
        public string Search { get; set; }
        public string Tags { get; set; }
        public Nullable<bool> Toggle { get; set; }
        public Nullable<int> ArticleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual tblArticle tblArticle { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
